<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Example forms using the Forms API.
 */

/**
 * Implements hook_form_alter().
 */
function aa_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // If this is the user login form, change the description text of the username
  // field.
  dpm($form_id);
  if ($form_id === 'user_form') {
    
    $form['name']['#description'] = t('Hola - username description');
    $form['mail']['#description'] = t('Hola - mail description');
  }

}
