<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\UserInterface;

/**
 * @file
 * Customization for user login, registration and more.
 */

/**
 * Implements hook_form_alter().
 */
function aa_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'user_register_form') {
    $form['account']['pass']['#required'] = FALSE;
    $form['account']['pass']['#access'] = FALSE;
  }

  if ($form_id === 'user_login_form') {
    $staff = \Drupal::request()->query->get('staff');
    // All Venezolans will have to just log in with their
    // "Cédula de Identidad o DNI" as the password.
    if (!$staff) {
      $form['pass']['#required'] = FALSE;
      $form['pass']['#access'] = FALSE;
      array_unshift($form['#validate'], 'aa_core_user_login_validate_pass');
      // Disable cache if query argument is ?staff
      $form['#cache']['contexts'][] = 'url.query_args:staff';
    }
  }

}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function aa_core_user_insert(UserInterface $user) {
  // Assign "Cédula de Identidad o DNI" as the password.
  if (!$user->hasRole('administrator') ||
    !$user->hasRole('equipo') ||
    !$user->hasRole('administrator' ||
    !$user->hasRole('misionero'))) {
    $user->pass->value = $user->label();
    $user->save();
  }
}

/**
 * Valitation callback for aa_core_form_alter().
 */
function aa_core_user_login_validate_pass(array $form, FormStateInterface $form_state) {
  $name = $form_state->getValue('name');
  $form_state->setValue('pass', $name);
}
