<?php

// /**
//  * @file
//  * Handles integration of Twig templates with the Drupal theme system.
//  */

/**
 * Implements hook_theme().
 */
function aa_report_theme($existing, $type, $theme, $path) {
    return [
    'aa_report_user_deliveries_total_block' => [
        'variables' => [
            'total_users' => NULL, 
            'total_deliveries' => NULL
            ],
        ],
    ];
}
